### ISSUE TITLE
✏️ [ FEAT REQ ]  Download attachments

### ISSUE THREAD

**Issue by mrtootoo** [octoshrimpy/quik#102]
To have the ability to download images and other attachments to the device.

I.E.  Be able to save an attach image to the download directory so that Quik is not needed to re-open image.

**Comment by parkersprouse** [comment]
If you tap on an image in a message to open it fullscreen, and then tap the three dots in the top right corner, do you have a "Save to gallery" option? I've always had that available to me in QUIK and it's how I locally save images sent to me

**Comment by octoshrimpy** [comment]
@parkersprouse is correct: 

kebab menu top right (`⋮`), save to gallery.
