### ISSUE TITLE
❓ [ QUESTION ]  App not installed as package conflicts with existing package. Do I need to delete old quik apk and install the new apk, or how to update? 

### ISSUE THREAD

**Issue by Hwmpunk** [octoshrimpy/quik#109]
If I need to delete then I need to backup 120k messages first, only reason I'm hesitant. Otherwise is there a way to update quik without deleting first? Thanks!

**Comment by octoshrimpy** [comment]
quik has an option to sync with/to sms db in the settings menu. you do not have to backup anything. 

Trigger that sync, then uninstall and reinstall the new version. :)

**Comment by CKMz17** [comment]
> quik has an option to sync with/to sms db in the settings menu. you do not have to backup anything. 
> 
> Trigger that sync, then uninstall and reinstall the new version. :)

It’s not exactly true, the settings are lost.
Is there no way to avoid conflicts? Otherwise, it would be useful to include the settings in the backup file so that they can be restored.
Thanks for your work
