### ISSUE TITLE
✏️ [ FEAT REQ ] Display the number of characters I can type to fit in message

### ISSUE THREAD

**Issue by P9NS5YVB851J50G** [octoshrimpy/quik#135]
**Is your feature request related to a problem? If so, please describe the problem.**
I write long messages sometimes and it would be nice to know how many more characters I can type to avoid splitting of my message.

**Describe the feature you'd like**
Some apps show the number of characters I can type to avoid splitting and the number of messages to send.
It would be great to see this feature in your app!

**Additional context**
![splitting of messages](https://github.com/user-attachments/assets/0d5faa9d-1410-4ccf-9bba-aa8fef0f1bbc)

**Comment by lascapi** [comment]
Hi, it's already there. 

You have to write more than 130 letters, but then you have exactly what you show.

**Comment by P9NS5YVB851J50G** [comment]
Hello!
Jesus, you are right!
Sorry, my bad.
I installed QUIK today and I'm still testing it.
It makes I love this app more.
