### ISSUE TITLE
:lady_beetle: [BUG] Type name input bar loses padding

### ISSUE THREAD

**Issue by CamdenCornwall** [octoshrimpy/quik#140]
**Describe the bug**
After tapping the cursor in the "Type a name or number" input, the input padding shrinks to match the character size. Correlates to the keyboard popping up.  

**To Reproduce**
1. After first opening the app click the "+" icon in the bottom right corner
2. Cursor should immediately be in "Type a name or number" input and keyboard pops up
3. Input will lose padding and default to text height

**Expected behavior**
Input bar should have a consistent padding

**Smartphone:**
 - Device: Pixel 4A
 - OS: Android 13
 - App Version: 4.0.7

**Screenshots**
![Screenshot_20240726-085614](https://github.com/user-attachments/assets/a9fa6f34-34d5-4b27-80e6-a1ade3aa9d4c)

**Additional context**
Same behavior with Gboard and FUTO Keyboard

**Comment by octoshrimpy** [comment]
i cannot replicate. looking deeper.

**Comment by octoshrimpy** [comment]
I _can_ replicate

**Comment by 4jNsY6fCVqZv** [comment]
@octoshrimpy Does the new height now correspond to the height of the ‘Search inbox’ field?

**Comment by octoshrimpy** [comment]
@4jNsY6fCVqZv correct!
