### ISSUE TITLE
✏️ [ FEAT REQ ] Apply CATEGORY_APP_MESSAGING so other apps know to use quik

### ISSUE THREAD

**Issue by jstride** [octoshrimpy/quik#169]
**Is your feature request related to a problem? If so, please describe the problem.**
Quik is not registering itself for default messaging app for SMS

**Describe the feature you'd like**
Other apps open Quik as the default messaging app (such as Smart Spacer)

**Additional context**

- https://github.com/KieronQuinn/Smartspacer/issues/261#issuecomment-2440563607
- https://developer.android.com/reference/android/content/Intent#CATEGORY_APP_MESSAGING

**Comment by octoshrimpy** [comment]
@jstride will have an APK for you this weekend. (ping me on matrix if I forget, pretty please)

**Comment by octoshrimpy** [comment]
@jstride https://github.com/octoshrimpy/quik/releases/tag/v4.0.8-alpha new alpha release with a couple bug fixes and the APP_MESSAGING fix

**Comment by jstride** [comment]
I've loaded that version - it still doesn't open when clicking through for me and defaults to the ASOP messages. Is there anything in the app I need to change?

**Comment by jstride** [comment]
I've loaded that version - it still doesn't open when clicking through for me and defaults to the ASOP messages. Is there anything in the app I need to change?

![Screenshot_20241102-163948.png](https://github.com/user-attachments/assets/684efe09-bf09-4574-baec-931264a62411)

its set as default but doesn't launch on smart space for me

**Comment by octoshrimpy** [comment]
@KieronQuinn Would you be willing to help me get this working? I've declared the intent with [this commit](https://github.com/octoshrimpy/quik/commit/a24e21d2f76ef0687e5df8112c447890a2e190f4) and the telephony permissions look (and work) okay as far as I can tell. Unsure why it's not working..

**Comment by KieronQuinn** [comment]
> @KieronQuinn Would you be willing to help me get this working? I've declared the intent with [this commit](https://github.com/octoshrimpy/quik/commit/a24e21d2f76ef0687e5df8112c447890a2e190f4) and the telephony permissions look (and work) okay as far as I can tell. Unsure why it's not working..

Add `android.intent.category.DEFAULT` as well as APP_MESSAGING, this seems to be required for it to appear on the picker

**Comment by octoshrimpy** [comment]
Thank you!

@jstride try the spacerpatch apk from [this pre-release](https://github.com/octoshrimpy/quik/releases/tag/v4.0.8-beta)

**Comment by jstride** [comment]
Perfect, that worked! Thank you so much!

**Comment by octoshrimpy** [comment]
sweeeet
