### ISSUE TITLE
❓ [ QUESTION ] Mark testing versions as beta

### ISSUE THREAD

**Issue by hrshtein** [octoshrimpy/quik#175]
The recent releases of quik are alpha or beta releases but are not marked as beta in github due to this the beta releases are termed as latest releases and pushed as update in obtainium.

**Comment by zer0fl0w** [comment]
yes, so does the v4.0.8 alpha, which force closes instantly and is not usable on gos a15.

**Comment by Pinaz993** [comment]
Can confirm, it was crashing on launch, and clearing the app data did help. How er, this forces a message re-sync, which can take a while to accomplish, depending on the amount of messages. On a slightly different topic, could syncing messages be multi-threaded? In my uninformed opinion, that seems like something that could be paralellized.

**Comment by octoshrimpy** [comment]
been fixed with any APK from [this pre-realease](https://github.com/octoshrimpy/quik/releases/tag/v4.0.8-beta). Will be more careful (and learn how to push pre-release tags)
