### ISSUE TITLE
RCS Support

### ISSUE THREAD

**Issue by MetalZealot** [octoshrimpy/quik#22]
RCS Support, with visual distinctions for RCS messages and regular SMS messages

*Only just discovered how RCS works _after_ I posted this, please disregard

**Comment by octoshrimpy** [comment]
For those finding this, RCS is currently a walled garden with Googs and Sammy being the only ones invited to the pool party. I, too, wish it were truly decentralized foss, but alas. Closing issue. Feel free to re-open this if the above circumstances change.  :)

**Comment by MetalZealot** [comment]
Thank you, I am new and ignorant 😓

**Comment by allanonmage** [comment]
I saw you make similar comments on the original QKSMS page.  Where can I go learn what you learned?  The fluff pieces I found were positive and promoted it as a new interoperability standard.  One of my non techy friends had told me about it a while back, saying that now that messages are encrypted, he wouldn't need to use Threema.  I wasn't aware of it at the time and didn't pursue it.

**Comment by KhazAkar** [comment]
As of RCS, have you seen this test RCS app in AOSP? https://android.googlesource.com/platform/packages/services/Telephony/+/master/testapps/TestRcsApp/
Maybe that might push this topic further

**Comment by K0-RR** [comment]
https://github.com/octoshrimpy/quik/issues/124
