### ISSUE TITLE
❓ [ QUESTION ] Is this App suited to be stock app on Lineage, Graphene etc?

### ISSUE THREAD

**Issue by firefoxlover** [octoshrimpy/quik#30]
Especially GrapheneOS focuses on secure and minimal apps for its pure SMS feature. Is this app suited for that purpose?

Can it handle and use system app privileges?

What security measurements are taken to secure it?

GrapheneOS ships the horrible AOSP sms app that is very outdated

**Comment by octoshrimpy** [comment]
Im unsure. If someone has more info on this, please share!

**Comment by octoshrimpy** [comment]
Very well said, @matchboxbananasynergy! any app can be installed and granted SMS permissions, it does not have to be a system app to interact with the internal SMS systems. 

As far as shipping as stock app, those that run the ROMs would have to be the ones to set it up that way: LOS, eOS, GOS maintainers (like matchbox above).

@firefoxlover does this answer your questions? If so, let's close this issue (and I gotta make a questions issue template too!)

**Comment by firefoxlover** [comment]
Sorry for the late reply.

Not fully:

- is the app modular enough to work as a plain sms app?
- does it accept running as system app, and not ask for permissions anymore (I suppose no, as there is a dialog baked in)

These would be the things that decide if it can run as a system app. But I agree having the least amount of system apps is way better, and any app with permissions AND disabled battery optimization can replace it.

**Comment by octoshrimpy** [comment]
> * is the app modular enough to work as a plain sms app?

Yes. As it stands, the app is just an SMS app, and SMS functionality will always exist (unlike Signal)

> * does it accept running as system app, and not ask for permissions anymore (I suppose no, as there is a dialog baked in)

Any app can be installed as a system app. Once that is done, it will never ask the user for permissions, because the app runs from system, which is one level higher than user, as far as permissions.

> These would be the things that decide if it can run as a system app. But I agree having the least amount of system apps is way better, and any app with permissions AND disabled battery optimization can replace it.
