### ISSUE TITLE
:lady_beetle: [BUG] f-droid link available?

### ISSUE THREAD

**Issue by s-light** [octoshrimpy/quik#31]
Currently the link to f-droid in the readme.md is Brocken.
It points to
https://f-droid.org/repository/browse/?fdid=dev.octoshrimpy.quik
But that results in an 404 not Found.

**Comment by octoshrimpy** [comment]
That was because of the mass-replace from QKSMS to quik. I do need to fix that, and I need to publish, thank you!

**Comment by s-light** [comment]
thanks for your fast response!
i will try the Obtainium way...

**Comment by octoshrimpy** [comment]
heads-up, I think I goofed the latest release somehow (4.0.5), and obtainium only grabs up to 4.0.4. I'm looking into it, still unsure why.

**Comment by anghelos** [comment]
> heads-up, I think I goofed the latest release somehow (4.0.5), and obtainium only grabs up to 4.0.4. I'm looking into it, still unsure why.

Fairly certain you forgot to change the version number in the release. Even when installing 4.0.5 manually, the version number in the app says 4.0.4

**Comment by inson1** [comment]
@anghelos yes he forgot about that, but there is another issue

**Comment by octoshrimpy** [comment]
I think I found the issue! release coming soon.
