### ISSUE TITLE
✏️ [ FEAT REQ ] Outdated MMS Config Database

### ISSUE THREAD

**Issue by Retold3202** [octoshrimpy/quik#36]
**Is your feature request related to a problem? If so, please describe the problem.**
Quik is currently using a very outdated MMS config database from January 2018, that it inherited from QKSMS. It can be found [here](https://github.com/octoshrimpy/quik/tree/master/android-smsmms/src/main/res). This can cause issues with MMS compatibility and reliability.

**Describe the feature you'd like**
I'd like to see Quik use an updated MMS config database. For instance, GrapheneOS uses the same database as Google Messages for their included Messaging app, see [here](https://github.com/GrapheneOS/platform_packages_apps_Messaging/tree/14/res). This database is much more up to date.

**Additional context**
See @SkewedZeppelin's comments [here](https://discuss.privacyguides.net/t/what-is-your-private-phone-setup/97/73) and [here](https://discuss.privacyguides.net/t/what-is-your-private-phone-setup/97/76).

**Comment by octoshrimpy** [comment]
Will be looking into this for the next release, as this seems important.

**Comment by octoshrimpy** [comment]
@Retold3202 I'm tackling this now, and after looking over everything, I think I understand what needs to be done, but not quite what needs to change, code-wise.

**Comment by SkewedZeppelin** [comment]
@octoshrimpy 
it shouldn't need any code changes, just dump the new ones in, but there is a possible question of licensing

**Comment by octoshrimpy** [comment]
@SkewedZeppelin Hey, great to see you here!

Good point on licensing. Do you know where I should start looking into that? maybe grapheneOS license, maybe?

**Comment by SkewedZeppelin** [comment]
@octoshrimpy 
no, you must understand those configs are dumped from decompiled Google Messenger.
they are a legal grey area.

**Comment by allanonmage** [comment]
Oh is that why QKSMS MMS broke a few years ago?  What does this configuration do that the APN on the network doesn't?

I tried to go look at them, and on the GrapheneOS page, there's a bunch of stuff about translations, so maybe I missed something.

**Comment by SkewedZeppelin** [comment]
@allanonmage 
APN configs are distinct from MMS configs.

**Comment by allanonmage** [comment]
Well now that the open source community has some code about all this, maybe I can figure out what's what and why MMS has never really worked on my phone whenever I load custom ROMs and stuff to it.

**Comment by snaggen** [comment]
About the licensing? Is that really any different from the existing outdated mms config? A assume they were aquired in the same/similar way? 
I think upgrading will not change the situation in this regard, but IANAL so... but if someone would raise an issue about it, then you can always revert. 

I think updating this configs to get MMS working properly should be quite high on the priority list....

**Comment by octoshrimpy** [comment]
@snaggen : agreed. Pinning this so when I get some time this is my first priority

**Comment by Jeroslav** [comment]
Hello, I'm happy to use this app. Thank You. I also have a problem with send eg. photos via MMS. @octoshrimpy I'm sorry for escalating problem, but I wanted to ask you if implementation date is known? (the problem has already been reported some time ago)

**Comment by Retold3202** [comment]
Hopefully this can eventually be implemented, I would love to be able to stop using the stock AOSP Messaging app...
