### ISSUE TITLE
✏️ [ FEAT REQ ] Add to Google play

### ISSUE THREAD

**Issue by inson1** [octoshrimpy/quik#39]
Its the most used app store. But F-droid is more important imo. (and the obtainium fix too ofc)

**Comment by octoshrimpy** [comment]
I believe adding to google play requires getting a paid dev account, which I'm not quite ready for. I want the app (and my knowledge of the app) to be more stable, first. :)

**Comment by inson1** [comment]
@octoshrimpy good reason :) but at least give it "future idea" label :) thanks

**Comment by Pinaz993** [comment]
Glad I searched before asking. I really hope you can pull it off.

**Comment by ADTC** [comment]
It costs $25 one-time fee to put your first app on Google Play Store. (Subsequent apps are free, and it's not a subscription.)

If you have sponsors and donations, perhaps would you?

One major issue is that Google Play Protect feature will block the installation of QUIK until it's turned off (you can turn it on again after the app is installed):

![Image](https://github.com/user-attachments/assets/f6791581-e695-4092-8045-ebc7e3c47a5e)

**Comment by unforgettableid** [comment]
### Background

(I have Boomerang for Gmail installed.  Also, thankfully: I think I'm a reasonably good writer.  I also have experience with careful resending, and with emoji in subject lines, to try to get emails read.)

### My idea

Dear @octoshrimpy:  If I have time, I'd like to email the QKSMS creator, to ask him if you could take over his Google Play developer account.  Then maybe current QKSMS users could get upgraded to Quik SMS.  They could get bug fixes, new features, and any security fixes y'all might push out in the future.

The Quik team could get even more cash donations and GitHub contributions.

### Conclusion

A.)  Do you object to me emailing the QKSMS guy?

B.)  If you don't object:  What email address do you use for Quik development?  Is it simply ${your_github_username} at gmail dot com?

Thank you for reading this.  And I thank all the Quik SMS contributors for all your efforts!  Have a good one.

**Comment by djibux** [comment]
I would love to see that app on the Play Store.  I have a corporate phone that is locked and I cannot install apps from 3rd party stores (or any apk).

**Comment by lorimode** [comment]
What's the status of this? Because it would be great if users who want a bit of open source/privacy could do so without too much hassle (just installing an APK, but that's complicated for some)...

Good day
