### ISSUE TITLE
🐞 [BUG] Obtainium - Problem with search and update

### ISSUE THREAD

**Issue by inson1** [octoshrimpy/quik#40]
https://github.com/octoshrimpy/quik/issues/31#issuecomment-1845760696

So anyway I asked https://github.com/ImranR98/Obtainium/issues/1170

**Comment by flame-0** [comment]
The latest version number is still 4.0.4, not 4.0.5, that's why.
![Screenshot_20231219-205904_App Manager](https://github.com/octoshrimpy/quik/assets/40175769/53a7e3f1-b0e0-4961-9004-fd636d316ffa)

**Comment by octoshrimpy** [comment]
ah that makes sense. I think I figured out where I have to update the version number. thank you for looking into it for me! there should be a new release coming soon

**Comment by ThreeDeeJay** [comment]
And so he rode into the sunset and was never heard from again.
jk but fr tho, Obtainium's still stuck and my OCD senses are tingling
version bump? 👀

**Comment by inson1** [comment]
maybe the problem with search is that this is fork? it would be worth it to read documentation about that
its just a idea, that I read somewhere

**Comment by octoshrimpy** [comment]
> And so he rode off into the sunset and was never heard from again. jk but fr tho, Obtainium's still stuck and my OCD senses are tingling, and it keeps downloading and reinstalling the same APK in the background😩 version bump? 👀

I was very sick for all of january, but am on the mend. I should be able to put effort into quik relatively soon!

**Comment by ThreeDeeJay** [comment]
Dang, been there. Hope you get better soon 🙏
In the meantime, we can just set it to track only and exclude it from notifications and background updates

**Comment by inson1** [comment]
Get better soon :)

**Comment by inson1** [comment]
yes, problem is that this is fork, if I search "quik fork:only" then I can find it
https://docs.github.com/en/search-github/searching-on-github/searching-in-forks

**Comment by octoshrimpy** [comment]
This has been fixed. :smile:  
( and I might even I know how I fixed it! )

**Comment by inson1** [comment]
@octoshrimpy what? How?

**Comment by octoshrimpy** [comment]
> @octoshrimpy what? How? search is still bad

I confirmed across 3 devices obtainium is able to grab the latest version, v4.0.6.  Can you explain what you've done/tried?

**Comment by inson1** [comment]
@octoshrimpy and the search works? if I search quik I cant find it (becase its fork)

**Comment by Yolakalemowa** [comment]
Hi can someone please help with this? Current Quik version is 4.3.4 but my obtanium refuses to update from 4.1.1, when I press update it give sme error: conflict [quik].

How to solve this? 

phone is Oppo reno4 Android 12. 

Obtanium version 1.3.4

**Comment by Inhishonor** [comment]
@Yolakalemowa You will have to uninstall the old version as we had to change our signing keys. You can find more information here: https://github.com/quik-sms/quik/releases/tag/v4.3.1. Sorry about that.

**Comment by Yolakalemowa** [comment]
@Inhishonor strange thing is that I only faced this issue on one device. On my other device it updated fine. any theories why?
