### ISSUE TITLE
:lady_beetle: [BUG] Release filenames use the name QKSMS insteead of QUIK/quik, which is the new project name

### ISSUE THREAD

**Issue by allanonmage** [octoshrimpy/quik#42]
**Describe the bug**
Release filenames use the name QKSMS insteead of QUIK/quik, which is the new project name

**To Reproduce**
1. Go to release page
2. Click on the link
3. See the filename

**Expected behavior**
Project rebranding should be part of step 0 or step 1 after forking, depending on how you start counting.

**Smartphone (please complete the following information):**
n/a

**Screenshots**
n/a

**Additional context**
n/a

**Comment by Zulgrib** [comment]
Not renaming makes migrating easier for Fdroid version.

**Comment by allanonmage** [comment]
In what way?  Getting banned for impersonating a project?

**Comment by octoshrimpy** [comment]
This has been completed
