### ISSUE TITLE
:lady_beetle: [BUG] Cannot name a conversation

### ISSUE THREAD

**Issue by strider72** [octoshrimpy/quik#46]
**Describe the bug**
Go into a conversation and try to set Conversation Title. App either crashes outright, or closes the rename dialog without doing anything

**Smartphone (please complete the following information):**
 - Device: Pixel 4a running CalyxOS with microG
 - OS: Android 14 (current)
 - App Version 4.0.4

**Comment by foolishgrunt** [comment]
Was just coming here to report this. Confirmed on LineageOS for MicroG 20.0.

Also running version 4.04 (because that's the latest version fetched by Obtainium - I believe I read that Dev is aware of this issue).

**Comment by foolishgrunt** [comment]
Duplicate of https://github.com/octoshrimpy/quik/issues/13?
