### ISSUE TITLE
Potential intellectual property issue

### ISSUE THREAD

**Issue by SilverPuppy** [octoshrimpy/quik#54]
"Quik" is a registered trademark of the Nestlé corporation. Though they're not actively using it at present, I doubt they'd appreciate having something so similar, differing only by capitalization of Q, used on something else.

https://en.m.wikipedia.org/wiki/Nesquik

Just something to consider. I applaud the reviving of this project, though I wonder why it needed to be forked to do so.

**Comment by 87113** [comment]
Hi, There is also a GoPro Quik App... 

I'm not a layer but I know that's possible to have the same brand in different industry : 

> The short answer is yes, it is possible for more than one company to have trademark rights in the same word or phrase in different industries. Examples of this include Delta (for faucets and airlines) and Pioneer (for electronics and agricultural seeds). 
> https://www.avvo.com/legal-answers/can-i-use-a-trademarked-name-in-a-different-indust-2672153.html

**Comment by octoshrimpy** [comment]
neither of those are in the SMS/messaging space so I believe it will be okay.
