### ISSUE TITLE
:lady_beetle: [BUG] v4.0.7 fails to start

### ISSUE THREAD

**Issue by sphh** [octoshrimpy/quik#65]
**Describe the bug**
After update to v4.0.7 QUIK fails to start.

**To Reproduce**
1. Update to v4.0.7
2. Start QUIK
3. `QUIK has stopped` Tap `Open app again`
4. `QUIK keeps stopping`

**Expected behavior**
Obviously QUIK should start.

**Smartphone (please complete the following information):**
 - Device: Unihertz Jelly Pro
 - OS: Android 8.1
 - App Version: 4.0.7

**Additional context**
I updated with the help of Optainium.
I downloaded https://github.com/octoshrimpy/quik/releases/download/v4.0.6/QUIK-noAnalytics-release.apk, but Android refuses to install it.

This is not much information to go on, so please tell me, what you need and I will try to get the information.

**Comment by sphh** [comment]
I now downgraded by uninstalling QUIK and installing v4.0.6. This version works fine.

**Comment by spoodfoilage** [comment]
Having the same issue with v4.0.7 on a Pixel 5 running Android 14.  Also had to uninstall and roll back to v4.0.6 which works without issues.

**Comment by sphh** [comment]
I installed the latest version (from an hour ago) and QUIK starts again.

Thanks for the quick fix!

**Comment by spoodfoilage** [comment]
I realize this is closed, but I also wanted to confirm that I newly installed the new v4.0.7 and it's working great.   And I also wanted to acknowledge and thank you for such a fast fix!
