### ISSUE TITLE
❓ [ QUESTION ]  Why can't update over the previous version 4.0.6?

### ISSUE THREAD

**Issue by oloukanov** [octoshrimpy/quik#66]
Why can't update over the previous version 4.0.6, changed signing keys?

On attempt, I receive:
**App not installed as package conflicts with an existing package.**

**Comment by octoshrimpy** [comment]
uninstall 4.0.6 and install 4.0.7. nothing will be lost. the new version is a properly signed release, instead of an unsigned debug version :)

**Comment by oloukanov** [comment]
Yeah, I know that but thanks for your time to reply.

The app settings will be lost and currently, there is no option to export them. Maybe I should submit a feature request, too. ;-)

I was worried not about reinstalling, but what prevented it from updating since the last two version upgrades went as expected. My 1st thought was "hacked dev's account and malicious release published".
