### ISSUE TITLE
❓ [ QUESTION ]  Why is there an "QUIK+ - deprecated" string at this point?

### ISSUE THREAD

**Issue by qvsojBJGiEnR** [octoshrimpy/quik#73]
https://github.com/octoshrimpy/quik/blob/b7923f20898b02e7c26ec161f8d2ec0281f8b69f/presentation/src/main/res/values/strings.xml#L33

This is also visible in the application window itself.

**Comment by octoshrimpy** [comment]
This was a regex  rename of QKSMS+. I have not yet gone through and removed references to it. The next release will remove all visible ones, and then I'll go through the codebase and actually remove unnecessary references like that. :)
