### ISSUE TITLE
✏️ [ FEAT REQ ] Update the copyright information

### ISSUE THREAD

**Issue by qvsojBJGiEnR** [octoshrimpy/quik#77]
**Is your feature request related to a problem? If so, please describe the problem.**

Visible for users in Settings > About.
Does not show the current development status

In the code https://github.com/search?q=repo%3Aoctoshrimpy%2Fquik%20copyright&type=code

**Comment by octoshrimpy** [comment]
fixed by #79

**Comment by octoshrimpy** [comment]
i'm still looking into it, because I don't know what would be considered my copyright vs moez's, when I modify a file.
