### ISSUE TITLE
Unlink it from QKSM

### ISSUE THREAD

**Issue by inson1** [octoshrimpy/quik#81]
Why? so people on Obtanium/Github can find it better
searching for forks isnt good
continuation of https://github.com/octoshrimpy/quik/issues/40

now
you cant find it 
https://github.com/search?q=quik+language%3AKotlin+&type=repositories

you have to allow forks
https://github.com/search?q=quik+fork%3Atrue+language%3AKotlin+&type=repositories

**Comment by savionlee** [comment]
I had to  favorite the repo for quick access

**Comment by octoshrimpy** [comment]
reached out to github support about it. in the works. :+1:

**Comment by inson1** [comment]
interesting if it is possible to get from support

**Comment by octoshrimpy** [comment]
done!
